### ISSUE TITLE
Destination Variables as Env Variables

### ISSUE THREAD

**Issue by smhmd** [enjuus/chdl#1]
Consider assigning `$ch_board`, `$ch_thread`, and `$ch_thread_id` in the session.

The example command from README would become:
```fish
$ chandler -s http://boards.4chan.org/wg/thread/7289180 -d "/home/user/pictures/$ch_board/$ch_thread"
```

More scriptable and Unixy that way.

---
Can you also add a flag to only assign the `$ch_*` variables without downloading?

**Comment by ncfavier** [comment]
It's unclear what you mean by "assigning variables in the session". An external program can't modify the shell's internal state (including variables); it would have to output the variables in shell syntax, and the user would have to run something like `source <(chandler -s URL ...)`, which seems impractical.

Since you already know what board and thread you are querying, why not set those variables yourself?

    ch_board=wg
    ch_thread=7289180
    chandler -s "http://boards.4chan.org/$ch_board/thread/$ch_thread" -d "/home/user/pictures/$ch_board/$ch_thread"

**Comment by smhmd** [comment]
@ncfavier, you can't export env variables in Go?
![image](https://user-images.githubusercontent.com/46059092/80281707-95b88580-86fc-11ea-914e-a662ab8940c5.png)

> Since you already know what board and thread you are querying, why not set those variables yourself?

I might, but the script doesn't. By that logic, why have `{BOARD}` variable for the `-d` flag if you can set it yourself.

**Comment by smhmd** [comment]
env variables are literally superior to what you have as you can use them outside the `chandler` command. 

is this a `won't fix` issue, @enjuus?

**Comment by enjuus** [comment]
this is a literally is not needed issue, beacuse you can just set your env variable and use it in in the URL flag.

**Comment by ncfavier** [comment]
Exporting a variable doesn't mean your parent process sees it, it means your child processes will.

`export` is a shell *builtin*, not an executable program, which is why it works.

**Comment by smhmd** [comment]
How am I to get the `thread`, @enjuus? not even awk can do that. 

@ncfavier, I know. Does Go not have an equivalent for setting env variables *for child processes*?

**Comment by lwatsondev** [comment]
> How am I to get the `thread`, @enjuus? not even awk can do that.

How are you passing the thread URL to `chandler` in the first place if you don't know what thread it is?

**Comment by smhmd** [comment]
I would know the `thread_id`, not `thread`, @TheReverend403.

**Comment by ncfavier** [comment]
> @ncfavier, I know. Does Go not have an equivalent for setting env variables _for child processes_?

Are you suggesting that chandler should spawn a shell in which those variables are set, *à la* `pipenv shell` or something?

**Comment by enjuus** [comment]
@smhmd the `thread` is pulled from the 4chan thread. I fail to see what you even want to set here. All those placeholder variables are taken from the thread you download. If you want to always keep the same format you can easily do `ch_format = "/path/to/picture/{BOARD/THREAD"` and then call `chandler -s http://boards.4chan.org/wg/thread/7289180 -d $ch_format"`

**Comment by smhmd** [comment]
How to open the thing after it's done downloading, for a single instance?

![image](https://user-images.githubusercontent.com/46059092/80282079-ff399380-86fe-11ea-849c-cff97fe424b4.png)

(I still wanted to request more information in the form of env variables that could be very beneficial for scripting in general. i.e. description, time, archive_status).

**Comment by enjuus** [comment]
Those would be variables the scraper has to grab and a completely different issue than what is discussed here. Looking to add more data / variables is something I can look at.

**Comment by ncfavier** [comment]
Ok, so the core of your request is that chandler should be able to report some of its internal information to the shell, which might be a fair point of improvement; but the implementation you're suggesting is completely nonsensical, as you don't seem to understand how environment variables work.

A somewhat reasonable way to do this would be something like curl's `-w` flag: print the information you want on standard output, using a format string. But I'm not sure this is worth the effort, as you could just name the output files in a way that only depends on known variables (like the thread id and board).

**Comment by smhmd** [comment]
I thought about that first, but it could be messy. In Node, you can use something like https://www.npmjs.com/package/shelljs 
```js
const shell = require('shelljs');
shell.exec('export ENV_VARIABLE=ABRACADABRA');
```

a flag that prints all info and still downloads the thread would be fine, even though you'd lose on status updates.

**Comment by ncfavier** [comment]
> ```js
> const shell = require('shelljs');
> shell.exec('export ENV_VARIABLE=ABRACADABRA');
> ```

This spawns a **new shell** as a child process, which sets `ENV_VARIABLE` to `ABRACADABRA` and then immediately exits, **destroying that information forever**.

**Comment by smhmd** [comment]
I see, oops.
